import { Link, useParams } from 'react-router-dom'

const policyContent = {
  shipping: { title: 'Shipping, with care.', intro: 'Every PAIROZ order is packed with care and sent on its way with complimentary standard shipping.', sections: [['Delivery timelines', 'Orders are typically dispatched within 2 business days. Delivery usually takes 3–7 business days depending on your location. During launches and sale periods, dispatch may take a little longer.'], ['Shipping charges', 'Standard shipping within India is complimentary. Any available express shipping options and charges will be displayed during checkout.'], ['Track your order', 'Once your order is dispatched, you will receive an update with tracking details. For help with a delivery, please contact hello@pairoz.com.']] },
  returns: { title: 'A fit that feels right.', intro: 'We want you to feel wonderful in your PAIROZ pair. If it isn’t quite right, we’re here to help.', sections: [['Returns & exchanges', 'You may request a return or exchange within 7 days of delivery. Items must be unworn, undamaged and returned with their original packaging and tags.'], ['How to request', 'Write to hello@pairoz.com with your order details and the reason for your request. Our customer care team will guide you through the next steps.'], ['Refunds', 'Approved refunds are processed to the original payment method. Processing timelines vary by bank or payment provider. This demo storefront does not collect payments.']] },
  privacy: { title: 'Your privacy matters.', intro: 'We treat your personal information with the same care we put into everything we make.', sections: [['Information we collect', 'In this frontend demo, forms and interactions run locally in your browser. No personal information is sent to or stored by a PAIROZ backend.'], ['How information is used', 'A production PAIROZ website would use order and contact information only to fulfil requests, support customers and improve the shopping experience.'], ['Your choices', 'You can clear locally persisted cart and wishlist data from your browser storage at any time. Contact us with questions about this policy.']] },
  terms: { title: 'The thoughtful details.', intro: 'These terms describe the use of the PAIROZ website and its frontend-only shopping experience.', sections: [['Website experience', 'Product listings, prices, availability and checkout interactions shown here are illustrative mock data. No purchase or payment can be completed.'], ['Product imagery', 'Colours may vary slightly between screens. Product imagery and descriptions are for demonstration purposes and may not represent a final retail product.'], ['Questions', 'If you have questions about these terms, please contact hello@pairoz.com.']] },
}

export default function Policies() {
  const { policy } = useParams()
  const content = policyContent[policy] || { title: 'The useful details.', intro: 'A considered experience extends beyond the shoes. Find the information you need below.', sections: Object.entries(policyContent).map(([key, item]) => [key[0].toUpperCase() + key.slice(1), item.intro]) }
  return <main className="page-wrap policy-page"><div className="breadcrumbs"><Link to="/">Home</Link><span>/</span><Link to="/policies">Policies</Link>{policy && <><span>/</span>{policy}</>}</div><header className="editorial-page-heading"><p className="eyebrow">The fine print, made human</p><h1><em>{content.title}</em></h1><p>{content.intro}</p></header><section className="policy-content">{content.sections.map(([title, body]) => <article key={title}><h2>{title}</h2><p>{body}</p></article>)}</section></main>
}
